# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0e4cb75ac930654d25854fc291042c9542d941610970e0ab5e9c0e5ce3044cba2bb56e261ebb884d3010eeeabf952038196c59bfff019221a736db31153fb6d

test:
  secret_key_base: 75906b3d6e7fc537b22ce8551d8fac0da1e0135012d84234d42de8843821bad8add1ff02c672191da98bfc95e82b2aeb0f93079653ac51b57dd48734ed3017e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
